[tool.yapf]
based_on_style = "pep8"
column_limit = 100
split_penalty_after_opening_bracket = 500
split_penalty_for_added_line_split = 1000
split_before_named_assigns = false
split_before_expression_after_opening_paren = false
